// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TagAlong.User.Infrastructure.Persistence;

#nullable disable

namespace TagAlong.User.Infrastructure.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260921000002_AddSmileUserId")]
    partial class AddSmileUserId
    {
    }
}
